// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyX773tG3rwNk6txsSWZxCTu9Tl9WQvLI',
    appId: '1:326127959271:web:1ec99cf1ec91474c64f642',
    messagingSenderId: '326127959271',
    projectId: 'flutterreason',
    authDomain: 'flutterreason.firebaseapp.com',
    storageBucket: 'flutterreason.firebasestorage.app',
    measurementId: 'G-FSY39ZB7EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtA25sZEspAPcdg72yyYauwSOM_PN6ThA',
    appId: '1:326127959271:android:e1f3be35130a1d8564f642',
    messagingSenderId: '326127959271',
    projectId: 'flutterreason',
    storageBucket: 'flutterreason.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6uETEIl2j3zzzMIaIC1Gh8dgj55AKcOw',
    appId: '1:326127959271:ios:a72c17083dbb701464f642',
    messagingSenderId: '326127959271',
    projectId: 'flutterreason',
    storageBucket: 'flutterreason.firebasestorage.app',
    iosBundleId: 'reason.iosFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6uETEIl2j3zzzMIaIC1Gh8dgj55AKcOw',
    appId: '1:326127959271:ios:a4f40bf993afea5364f642',
    messagingSenderId: '326127959271',
    projectId: 'flutterreason',
    storageBucket: 'flutterreason.firebasestorage.app',
    iosBundleId: 'com.example.iosFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyX773tG3rwNk6txsSWZxCTu9Tl9WQvLI',
    appId: '1:326127959271:web:d4ace19ab95dbf5564f642',
    messagingSenderId: '326127959271',
    projectId: 'flutterreason',
    authDomain: 'flutterreason.firebaseapp.com',
    storageBucket: 'flutterreason.firebasestorage.app',
    measurementId: 'G-MNH0CZMXRT',
  );
}
